package tt.demo.mybatis.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tt.demo.mybatis.model.Customer;
import tt.demo.mybatis.model.CustomerExample;

public interface CustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int countByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int deleteByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int insert(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int insertSelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	List<Customer> selectByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	Customer selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int updateByPrimaryKeySelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Fri Aug 12 01:10:08 KST 2016
	 */
	int updateByPrimaryKey(Customer record);
}